"""
LSADRA V4 — Pure-template narrative engine.

Extends V3's NarrativeBuilder class (preserved) with V4 functions:
  - generate_alert_narrative()       per-alert 2-3 sentence narrative
  - generate_investigative_summary() full multi-paragraph case file
  - format_timeline_text()           human-readable chronological summary
  - get_shap_narrative_fragment()    converts V3 SHAP output to prose
  - get_confidence_level()           corroborating signal count → confidence
  - analyze_false_positive()         pure decision-tree FP analysis

[DESIGN CHOICE] Zero-dependency narrative engine. Structured template logic
produces deterministic, auditable explanations without vendor lock-in or
runtime cost. Uses shap_values already generated by V3 explainability module.

[MYTHOS ALIGNMENT — human-readable incident narrative]
[MYTHOS ALIGNMENT — structured investigation report]
[GLASSWING ALIGNMENT — analyst case file generation]

R8 boundary: every string interpolated into a template goes through
``clean_field`` (see ``sanitize.py``); numbers go through ``int``/``float``
format specs. Log-derived values are never placed inside markdown code spans,
where backslash escapes do not apply.
"""

import logging
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from lsadra.explainability.sanitize import (
    MAX_IDENT,
    MAX_IP,
    MAX_LABEL,
    MAX_TEXT,
    MAX_TIMESTAMP,
    clean_field,
    clean_list,
)

logger = logging.getLogger(__name__)


# ============================================================================
# V3 NarrativeBuilder (preserved exactly)
# ============================================================================

class NarrativeBuilder:
    """Produce analyst-friendly natural-language alert descriptions (V3)."""

    @staticmethod
    def build(
        threat_type: str,
        mitre_id: str,
        row_data: Dict[str, Any],
        layer1_z: float = 0.0,
        layer2_score: float = 0.0,
        layer3_error: float = 0.0,
        severity_context: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Construct a narrative string from detection context (V3).

        Args:
            threat_type:      Classified threat name.
            mitre_id:         MITRE ATT&CK technique ID.
            row_data:         Feature + metadata dict for the event.
            layer1_z:         Max z-score from statistical baseline.
            layer2_score:     Averaged score from classical ensemble.
            layer3_error:     Reconstruction error from autoencoder.
            severity_context: Optional dict with severity_score, severity_label, urgency.

        Returns:
            Multi-sentence narrative string.
        """
        ip     = clean_field(row_data.get("source_ip", "Unknown IP"), MAX_IP)
        user   = clean_field(row_data.get("effective_username", "Unknown"), MAX_IDENT)
        device = clean_field(row_data.get("device_id", "Unknown Device"), MAX_IDENT)

        sev_label = "MEDIUM"
        sev_score = 0.0
        urgency   = ""
        if severity_context:
            sev_label = severity_context.get("severity_label", "MEDIUM")
            sev_score = severity_context.get("severity_score", 0.0)
            urgency   = severity_context.get("urgency", "")

        sev_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(sev_label, "⚪")
        sev_label = clean_field(sev_label, MAX_LABEL)
        urgency   = clean_field(urgency, MAX_TEXT)

        parts = [
            f"{sev_emoji} **[{sev_label}]** **{clean_field(threat_type, MAX_LABEL)}** "
            f"detected ({clean_field(mitre_id, MAX_LABEL)}).",
            f"Source: **{ip}** → user **'{user}'** on device **{device}**.",
        ]

        if sev_score > 0:
            parts.append(f"Severity score: **{sev_score:.2f}**.")

        layer_reasons = []
        if layer1_z > 0:
            layer_reasons.append(f"statistical baseline deviation of {layer1_z:.1f}σ")
        if layer2_score > 0:
            layer_reasons.append(f"ensemble anomaly score of {layer2_score:.2f}")
        if layer3_error > 0:
            layer_reasons.append(f"autoencoder reconstruction error of {layer3_error:.4f}")
        if layer_reasons:
            parts.append("Flagged due to " + ", ".join(layer_reasons) + ".")

        failures     = row_data.get("failures_15m", 0)
        unique_users = row_data.get("unique_users_15m", 0)
        off_hours    = row_data.get("is_off_hours", 0)
        details = []
        if failures:
            details.append(f"{int(failures)} failed logins in 15 min")
        if unique_users and unique_users > 1:
            details.append(f"{int(unique_users)} unique usernames targeted")
        if off_hours:
            details.append("activity during off-hours")
        if details:
            parts.append("Context: " + "; ".join(details) + ".")

        if urgency:
            parts.append(f"**{urgency}**")

        advice_map = {
            "Brute Force Attack":     "Consider blocking the source IP and enforcing account lockout.",
            "Credential Stuffing":    "Verify MFA is enabled on targeted accounts.",
            "Low and Slow Attack":    "Monitor this IP over the next 24 hours.",
            "Anomalous Off-Hour Access": "Confirm whether this access was authorised.",
        }
        advice = advice_map.get(threat_type)
        if advice:
            parts.append(f"**Recommendation**: {advice}")

        return " ".join(parts)


# ============================================================================
# V4 narrative functions
# ============================================================================

def generate_alert_narrative(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    shap_values: Optional[Dict[str, float]] = None,
    entity_timeline: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Generate a 2-3 sentence alert narrative from V4 features and rule output.

    Gracefully degrades — if generation fails, returns a fallback string.

    [MYTHOS ALIGNMENT — human-readable incident narrative]
    [DESIGN CHOICE] Pure Python, zero external dependencies.

    Args:
        features:        Enriched V4 feature dict for the triggering event.
        rule_alert:      V4 rule alert dict (type, severity, mitre_id, etc.).
        shap_values:     Optional per-feature SHAP values from V3 explainability.
        entity_timeline: Optional ordered event history for the entity.

    Returns:
        Human-readable alert narrative string.
    """
    try:
        rule_type = rule_alert.get("type", "UNKNOWN")
        dispatcher = {
            "BRUTE_FORCE":       _narrate_brute_force,
            "CREDENTIAL_STUFFING": _narrate_credential_stuffing,
            "LOW_AND_SLOW":      _narrate_low_and_slow,
            "LATERAL_MOVEMENT":  _narrate_lateral_movement,
            "PORT_SCAN":         _narrate_port_scan,
            "LARGE_DATA_TRANSFER": _narrate_large_data_transfer,
            "SUSPICIOUS_PROCESS": _narrate_suspicious_process,
            "PRIVILEGE_ESCALATION": _narrate_privilege_escalation,
            "PERSISTENCE":       _narrate_persistence,
        }
        func = dispatcher.get(rule_type, _narrate_generic)
        narrative = func(features, rule_alert, entity_timeline)
        shap_frag = get_shap_narrative_fragment(shap_values)
        if shap_frag:
            narrative += f" {shap_frag}"
        return narrative
    except Exception:
        logger.exception("generate_alert_narrative failed — using fallback.")
        return f"Narrative unavailable: {clean_field(rule_alert.get('reason', 'unknown reason'), MAX_TEXT)}"


def _narrate_brute_force(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build brute force narrative."""
    ip          = clean_field(features.get("source_ip", "Unknown IP"), MAX_IP)
    failed_5min = int(features.get("failed_logins_last_5min", 0))
    failed_15min= int(features.get("failed_logins_last_15min", 0))
    velocity    = float(features.get("login_attempt_velocity", 0))
    uniq_users  = int(features.get("unique_usernames_per_ip", 0))

    sentence = (
        f"IP {ip} performed {failed_5min} failed login attempts in the last "
        f"5 minutes at {velocity:.1f} attempts/minute."
    )

    if failed_15min > failed_5min * 1.5:
        sentence += " Attack is accelerating over the 15-minute observation window."

    if uniq_users > 1:
        sentence += f" Targeting {uniq_users} distinct accounts."

    sentence += " Consistent with MITRE T1110.001 (Password Guessing)."
    return sentence


def _narrate_credential_stuffing(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build credential stuffing narrative."""
    ip          = clean_field(features.get("source_ip", "Unknown IP"), MAX_IP)
    uniq_users  = int(features.get("unique_usernames_per_ip", 0))
    fail_ratio  = float(features.get("failure_ratio", 0))
    cross       = bool(features.get("cross_source_activity", False))

    sentence = (
        f"IP {ip} attempted logins against {uniq_users} distinct usernames "
        f"with a {fail_ratio * 100:.0f}% failure rate."
    )
    if cross:
        sentence += " This IP is also observed in network flow data."
    sentence += " Consistent with MITRE T1110.004 (Credential Stuffing)."
    return sentence


def _narrate_low_and_slow(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build low-and-slow attack narrative."""
    ip       = clean_field(features.get("source_ip", "Unknown IP"), MAX_IP)
    velocity = float(features.get("login_attempt_velocity", 0))
    window   = 15

    sentence = (
        f"IP {ip} conducted a slow distributed attack across {window} minutes "
        f"maintaining {velocity:.2f} attempts/minute to evade detection thresholds."
    )
    if timeline and len(timeline) >= 2:
        first_ts = timeline[0].get("timestamp", "")[:16]
        last_ts  = timeline[-1].get("timestamp", "")[:16]
        if first_ts and last_ts:
            sentence += (
                f" Activity spans from {clean_field(first_ts, MAX_TIMESTAMP)} "
                f"to {clean_field(last_ts, MAX_TIMESTAMP)}."
            )
    sentence += " Consistent with MITRE T1110.003 (Password Spraying)."
    return sentence


def _narrate_lateral_movement(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build lateral movement narrative."""
    ip              = clean_field(rule_alert.get("ip") or features.get("source_ip", "Unknown IP"), MAX_IP)
    unique_devices  = clean_field(features.get("unique_ips_per_username", 0), MAX_LABEL)
    unique_users    = clean_field(features.get("unique_usernames_per_ip", 0), MAX_LABEL)
    affected_users  = rule_alert.get("affected_users", "")

    sentence = (
        f"Source IP {ip} accessed {unique_devices} devices and "
        f"{unique_users} accounts suggesting lateral movement."
    )
    if affected_users:
        users_list = clean_list(affected_users, max_items=5, max_len=MAX_IDENT)
        sentence += f" Affected accounts include: {users_list}."
    sentence += " Consistent with MITRE T1021 (Remote Services)."
    return sentence


def _narrate_port_scan(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build port scan narrative."""
    ip         = clean_field(features.get("source_ip", "Unknown IP"), MAX_IP)
    uniq_ports = int(features.get("unique_dst_ports_per_ip", 0))
    window     = 10

    sentence = f"IP {ip} probed {uniq_ports} destination ports in {window} minutes."
    sentence += " Consistent with MITRE T1046 (Network Service Discovery)."
    return sentence


def _narrate_large_data_transfer(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build large data transfer / exfiltration narrative."""
    device    = clean_field(features.get("device_id", "Unknown"), MAX_IDENT)
    bytes_out = float(features.get("total_bytes_out", 0))
    dest_ip   = clean_field(features.get("dest_ip") or "unknown destination", MAX_IP)
    mb        = bytes_out / 1_000_000

    sentence = (
        f"Host {device} transferred {mb:.1f} MB outbound to {dest_ip} "
        f"over 30 minutes, exceeding the normal baseline threshold."
    )
    sentence += " Consistent with MITRE T1048 (Exfiltration)."
    return sentence


def _narrate_suspicious_process(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build suspicious process / LOLBin narrative."""
    device       = clean_field(features.get("device_id", "Unknown"), MAX_IDENT)
    proc_count   = int(features.get("suspicious_process_count", 0))
    lolbin_count = int(features.get("lolbin_usage_count", 0))

    sentence = f"Device {device} executed {proc_count} suspicious processes."
    if lolbin_count > 0:
        sentence += f" LOLBin abuse detected ({lolbin_count} instance(s))."
    sentence += " Consistent with MITRE T1059 (Command and Scripting)."
    return sentence


def _narrate_privilege_escalation(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build privilege escalation narrative."""
    username = clean_field(
        features.get("username") or features.get("effective_username", "Unknown"), MAX_IDENT
    )
    device   = clean_field(features.get("device_id", "Unknown"), MAX_IDENT)
    count    = len(timeline) if timeline else 1
    window   = 15

    sentence = (
        f"User {username} on {device} performed {count} privilege "
        f"escalation events in {window} minutes."
    )
    sentence += " Consistent with MITRE T1548 (Abuse Elevation Control)."
    return sentence


def _narrate_persistence(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Build persistence mechanism narrative."""
    device     = clean_field(features.get("device_id", "Unknown"), MAX_IDENT)
    event_type = clean_field(features.get("event_type", "persistence event"), MAX_LABEL)
    src        = clean_field(features.get("source_type", "unknown source"), MAX_LABEL)

    sentence = (
        f"A persistence mechanism ({event_type}) was detected on device {device} "
        f"via {src}."
    )
    sentence += " Consistent with MITRE T1547 (Boot or Logon Autostart Execution)."
    return sentence


def _narrate_generic(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    timeline: Optional[List[Dict[str, Any]]],
) -> str:
    """Fallback narrative for unrecognised rule types."""
    ip     = clean_field(features.get("source_ip", "Unknown IP"), MAX_IP)
    reason = clean_field(rule_alert.get("reason", "anomalous activity detected"), MAX_TEXT)
    mitre  = clean_field(rule_alert.get("mitre_id", "unknown MITRE technique"), MAX_LABEL)
    return f"Suspicious activity from {ip}: {reason}. Related to {mitre}."


# ============================================================================
# Investigative summary
# ============================================================================

def generate_investigative_summary(
    ip: str,
    incident_data: Dict[str, Any],
    entity_timeline: List[Dict[str, Any]],
    similar_past_incidents: List[Dict[str, Any]],
    threat_intel: Optional[Dict[str, Any]],
) -> str:
    """
    Generate a full multi-paragraph investigation report for an IP.

    [MYTHOS ALIGNMENT — structured investigation report]
    [GLASSWING ALIGNMENT — analyst case file generation]
    [DESIGN CHOICE] Pure logic — no external dependencies.

    Args:
        ip:                      Source IP under investigation.
        incident_data:           Incident record dict from DB.
        entity_timeline:         Ordered event history for the IP.
        similar_past_incidents:  Previous incidents matching the IP/type.
        threat_intel:            Optional AbuseIPDB cache entry.

    Returns:
        Full investigation report as a formatted markdown string.
    """
    try:
        sections = [
            _para_executive_summary(ip, incident_data, entity_timeline, threat_intel),
            _para_attack_pattern(ip, incident_data, entity_timeline),
            _para_affected_assets(entity_timeline),
            _para_confidence(incident_data, entity_timeline, threat_intel),
            _para_recommendations(incident_data),
        ]
        if similar_past_incidents:
            sections.append(_para_historical_context(similar_past_incidents))
        return "\n\n---\n\n".join(filter(None, sections))
    except Exception:
        logger.exception("generate_investigative_summary failed for IP %r", ip)
        return f"**Investigation report unavailable for IP {clean_field(ip, MAX_IP)}.**"


def _para_executive_summary(
    ip: str,
    incident: Dict[str, Any],
    timeline: List[Dict[str, Any]],
    threat_intel: Optional[Dict[str, Any]],
) -> str:
    """Para 1: Executive summary."""
    ip        = clean_field(ip, MAX_IP)
    attack    = clean_field(incident.get("attack_type", "Unknown Attack"), MAX_LABEL)
    severity  = clean_field(incident.get("severity_label", "UNKNOWN"), MAX_LABEL)
    first     = clean_field(incident.get("first_seen", "")[:16], MAX_TIMESTAMP)
    last      = clean_field(incident.get("last_seen",  "")[:16], MAX_TIMESTAMP)
    cnt       = clean_field(incident.get("anomaly_count", len(timeline)), MAX_LABEL)

    ti_note = ""
    if threat_intel:
        score = clean_field(threat_intel.get("abuse_score", 0), MAX_LABEL)
        country = clean_field(threat_intel.get("country_code", ""), MAX_LABEL)
        ti_note = f" Threat intelligence: AbuseIPDB score {score}/100 (origin: {country})."

    return (
        f"## 📋 Executive Summary\n\n"
        f"**IP Address**: **{ip}** | **Attack Type**: {attack} | **Severity**: {severity}\n\n"
        f"This incident was first detected at **{first}** and was last observed at **{last}**, "
        f"generating {cnt} anomaly event(s).{ti_note}"
    )


def _para_attack_pattern(
    ip: str, incident: Dict[str, Any], timeline: List[Dict[str, Any]]
) -> str:
    """Para 2: Attack pattern analysis."""
    if not timeline:
        return "## 🔍 Attack Pattern\n\nInsufficient timeline data for pattern analysis."

    event_types = [e.get("event_type", "") for e in timeline]
    unique_types = list(dict.fromkeys(event_types))  # ordered unique

    sequence = " → ".join(clean_field(t, MAX_LABEL) for t in unique_types[:8])
    timeline_text = format_timeline_text(timeline)
    return (
        f"## 🔍 Attack Pattern\n\n"
        f"Observed event sequence: {sequence}\n\n"
        f"{timeline_text}"
    )


def _para_affected_assets(timeline: List[Dict[str, Any]]) -> str:
    """Para 3: Affected assets derived from timeline."""
    devices   = list({e.get("device_id", "") for e in timeline if e.get("device_id")})
    usernames = list({e.get("effective_username", "") for e in timeline if e.get("effective_username")})

    return (
        f"## 🖥️ Affected Assets\n\n"
        f"**Devices ({len(devices)})**: {clean_list(devices, max_items=10) or 'None identified'}\n\n"
        f"**Accounts ({len(usernames)})**: {clean_list(usernames, max_items=10) or 'None identified'}"
    )


def _para_confidence(
    incident: Dict[str, Any],
    timeline: List[Dict[str, Any]],
    threat_intel: Optional[Dict[str, Any]],
) -> str:
    """Para 4: Confidence analysis."""
    level, explanation = get_confidence_level(
        features={},
        rule_alert=incident,
        threat_intel=threat_intel,
        timeline=timeline,
    )
    badge = {"HIGH": "🟢 HIGH", "MEDIUM": "🟡 MEDIUM", "LOW": "🔴 LOW"}.get(level, level)
    return f"## 🎯 Detection Confidence\n\n**{badge}** — {explanation}"


def _para_recommendations(incident: Dict[str, Any]) -> str:
    """Para 5: Recommended actions based on attack type."""
    attack = incident.get("attack_type", "")
    recs = _get_recommendations(attack)
    lines = "\n".join(f"- {r}" for r in recs)
    return f"## ✅ Recommended Actions\n\n{lines}"


def _para_historical_context(past: List[Dict[str, Any]]) -> str:
    """Optional: Historical incident context."""
    count = len(past)
    types = list({i.get("attack_type", "") for i in past})[:5]
    return (
        f"## 📅 Historical Context\n\n"
        f"{count} related past incident(s) found. Previous attack types: "
        f"{clean_list(types, max_items=5, max_len=MAX_LABEL) or 'N/A'}."
    )


def _get_recommendations(attack_type: str) -> List[str]:
    """Return action recommendations for a given attack type."""
    base_recs = {
        "BRUTE_FORCE": [
            "Block source IP at firewall immediately.",
            "Enable account lockout policies.",
            "Force password reset for targeted accounts.",
            "Review authentication logs for successful break-ins.",
            "Consider deploying fail2ban or equivalent.",
        ],
        "CREDENTIAL_STUFFING": [
            "Enable multi-factor authentication on all affected accounts.",
            "Block source IP and associated ASN if possible.",
            "Check for successful logins from this IP and revoke sessions.",
            "Enable CAPTCHA on login forms.",
            "Monitor for credential re-use on other services.",
        ],
        "LATERAL_MOVEMENT": [
            "Isolate affected devices from the network immediately.",
            "Audit all accounts recently accessed from the source IP.",
            "Review firewall east-west traffic rules.",
            "Check for new user accounts or scheduled tasks.",
            "Engage incident response team for containment.",
        ],
        "PORT_SCAN": [
            "Block the scanning IP at perimeter firewall.",
            "Review which services are exposed on scanned ports.",
            "Check for subsequent exploitation attempts.",
            "Notify network admin to review ACLs.",
            "Monitor for targeted exploitation of discovered ports.",
        ],
    }
    generic = [
        "Document the incident with timestamps and source details.",
        "Preserve logs for forensic analysis before cleanup.",
        "Notify security operations team.",
    ]
    return bespoke if (bespoke := base_recs.get(attack_type)) else generic


# ============================================================================
# Helper functions
# ============================================================================

def format_timeline_text(timeline: List[Dict[str, Any]]) -> str:
    """
    Format an entity timeline into a grouped readable summary.

    Groups events by source_type, shows timestamps, counts, and transitions.

    Args:
        timeline: Ordered list of event dicts.

    Returns:
        Plain-text formatted timeline summary.
    """
    if not timeline:
        return "_No timeline data available._"

    lines: List[str] = []
    by_source: Dict[str, List[Dict[str, Any]]] = {}
    for event in timeline:
        src = event.get("source_type") or "unknown"
        by_source.setdefault(src, []).append(event)

    for src, events in by_source.items():
        first = clean_field(events[0].get("timestamp", "")[:16], MAX_TIMESTAMP)
        last  = clean_field(events[-1].get("timestamp", "")[:16], MAX_TIMESTAMP)
        types = ", ".join(
            clean_field(t, MAX_LABEL) for t in sorted({str(e.get("event_type", "")) for e in events})
        )
        lines.append(f"**{clean_field(src, MAX_LABEL)}** ({len(events)} events, {first} → {last}): {types}")

    return "\n".join(lines)


def get_shap_narrative_fragment(shap_values: Optional[Dict[str, float]]) -> str:
    """
    Convert V3 SHAP output into a readable sentence fragment.

    Example output:
        "driven primarily by high login velocity (SHAP: 0.42)"

    Args:
        shap_values: Dict of feature_name → SHAP value. May be None.

    Returns:
        Readable fragment string, or empty string if unavailable.
    """
    if not shap_values:
        return ""
    try:
        top_feat = max(shap_values, key=lambda k: abs(shap_values[k]))
        top_val  = shap_values[top_feat]
        readable = clean_field(str(top_feat).replace("_", " "), MAX_LABEL)
        return f"Analysis driven primarily by {readable} (SHAP: {top_val:.2f})."
    except (ValueError, TypeError):
        return ""


def get_confidence_level(
    features: Dict[str, Any],
    rule_alert: Dict[str, Any],
    threat_intel: Optional[Dict[str, Any]],
    timeline: List[Dict[str, Any]],
) -> Tuple[str, str]:
    """
    Determine detection confidence from corroborating signal count.

    HIGH   if >= 3 corroborating signals
    MEDIUM if 2 signals
    LOW    if 1 signal

    [DESIGN CHOICE] Signal-count heuristic is simple to audit and adjust
    without retraining ML models.

    Args:
        features:    Enriched V4 feature dict.
        rule_alert:  V4 rule alert dict.
        threat_intel: Optional AbuseIPDB cache entry.
        timeline:    Ordered entity event history.

    Returns:
        (level: str, plain_english_explanation: str)
    """
    signals: List[str] = []

    if rule_alert.get("rule_weight", 0) >= 0.7:
        signals.append("high-weight rule triggered")
    if threat_intel and threat_intel.get("abuse_score", 0) > 25:
        signals.append("malicious threat intel hit")
    if len(timeline) >= 5:
        signals.append("sustained event timeline (5+ events)")
    if features.get("cross_source_activity"):
        signals.append("cross-source IP corroboration")
    if float(features.get("failure_ratio", 0)) > 0.8:
        signals.append("high failure ratio (>80%)")

    count = len(signals)
    if count >= 3:
        return "HIGH", f"Confirmed by {count} corroborating signals: {'; '.join(signals)}."
    if count == 2:
        return "MEDIUM", f"Supported by {count} signals: {'; '.join(signals)}."
    explanation = signals[0] if signals else "single rule trigger with no corroboration"
    return "LOW", f"Single signal: {explanation}."


# ============================================================================
# False positive analysis
# ============================================================================

def analyze_false_positive(
    original_alert: Dict[str, Any],
    analyst_note: str = "",
) -> Dict[str, Any]:
    """
    Analyse an alert for known false-positive patterns via pure decision tree.

    [MYTHOS ALIGNMENT — adaptive feedback reasoning]
    [DESIGN CHOICE] Pure Python decision tree, no LLM required.

    Examines feature values against known FP patterns:
      - Low-velocity single-account (monitoring/automation)
      - Large overnight transfer (backup job)
      - LOLBin in backup/admin tool cmdline
      - CI/CD burst logins

    Args:
        original_alert: Full alert dict (should include features, rule_type, etc.).
        analyst_note:   Optional free-text note from the analyst.

    Returns:
        Dict with pattern, suggested_threshold_change, missing_context, confidence.
    """
    features   = original_alert.get("features", {})
    rule_type  = original_alert.get("type", "UNKNOWN")
    velocity   = float(features.get("login_attempt_velocity", 0))
    uniq_users = float(features.get("unique_usernames_per_ip", 0))
    bytes_out  = float(features.get("total_bytes_out", 0))
    lolbin     = float(features.get("lolbin_usage_count", 0))
    failed_5m  = float(features.get("failed_logins_last_5min", 0))
    device     = features.get("device_id", "")

    note_lower = analyst_note.lower()

    # --- Pattern 1: Monitoring/automation burst (low-velocity, single user) ---
    if (rule_type == "BRUTE_FORCE" and uniq_users <= 1 and velocity < 0.5):
        return _fp_result(
            "monitoring_automation",
            {"failed_logins_last_5min": max(int(failed_5m * 1.5), 10)},
            "Service account / monitoring tool generating repeated auth checks.",
            "MEDIUM",
        )

    # --- Pattern 2: Large overnight backup transfer ---
    if (rule_type == "LARGE_DATA_TRANSFER" and bytes_out > 10_000_000):
        hour = _get_event_hour(original_alert)
        if hour is not None and (hour < 6 or hour >= 22):
            return _fp_result(
                "backup_job",
                {"total_bytes_out": int(bytes_out * 1.25)},
                "Overnight large transfer — likely scheduled backup job.",
                "HIGH",
            )

    # --- Pattern 3: LOLBin in admin/backup tooling ---
    if (rule_type == "SUSPICIOUS_PROCESS" and lolbin > 0):
        if any(kw in note_lower for kw in ("backup", "admin", "deploy", "sccm", "ansible")):
            return _fp_result(
                "admin_tooling_lolbin",
                {"lolbin_usage_count": 2},
                "LOLBin used by known admin/backup tooling — whitelist candidate.",
                "HIGH",
            )

    # --- Pattern 4: CI/CD burst logins ---
    if (rule_type in ("BRUTE_FORCE", "CREDENTIAL_STUFFING")
            and any(kw in note_lower for kw in ("ci", "cd", "jenkins", "github", "deploy"))):
        return _fp_result(
            "cicd_burst",
            {"failed_logins_last_5min": int(failed_5m * 2)},
            "CI/CD pipeline authentication burst — automated deployment detected.",
            "MEDIUM",
        )

    # --- Default: no recognised FP pattern ---
    return _fp_result(
        "no_known_pattern",
        {},
        "No common false-positive pattern matched. Manual review required.",
        "LOW",
    )


def _fp_result(
    pattern: str,
    suggested_thresholds: Dict[str, Any],
    missing_context: str,
    confidence: str,
) -> Dict[str, Any]:
    """Build a standardised false-positive analysis result dict."""
    return {
        "pattern":                    pattern,
        "suggested_threshold_change": suggested_thresholds,
        "missing_context":            missing_context,
        "confidence":                 confidence,
    }


def _get_event_hour(alert: Dict[str, Any]) -> Optional[int]:
    """Extract the hour from an alert's timestamp if available."""
    ts = alert.get("timestamp") or alert.get("created_at", "")
    if not ts:
        return None
    try:
        return datetime.fromisoformat(str(ts)[:19]).hour
    except ValueError:
        return None
